
let state={questions:[],i:0,score:0,wrong:[],mode:'normal'};
const $=id=>document.getElementById(id);

const REVISION={
"Beith":{axes:"Renouveau · purification · croissance · foyer",symbolism:"Le bouleau est associé au recommencement et à la capacité de repartir sur un terrain clarifié. Sa blancheur renforce les idées de purification, de lumière et de nouveau cycle.",reading:"Beith annonce une ouverture : quelque chose peut naître, repartir ou être remis à neuf. Il invite à créer les conditions favorables au commencement plutôt qu'à rester attaché à l'ancien.",advice:"Fais de la place pour ce qui cherche à naître.",shadow:"Difficulté à commencer, peur du changement, attachement au passé ou précipitation.",associations:"Bouleau · naissance · purification · enfance · foyer",magic:"Travaux contemporains de renouveau, purification et ouverture de cycle."},
"Luis":{axes:"Discernement · protection · intuition · connaissance",symbolism:"Le sorbier réunit protection et clairvoyance. Il évoque la capacité à observer les signes, distinguer le vrai du trompeur et transformer la perception en choix juste.",reading:"Luis demande de regarder plus attentivement avant d'agir. Il peut signaler un besoin de protection, mais surtout la nécessité de comprendre ce dont on doit réellement se protéger.",advice:"Regarde clairement avant de choisir.",shadow:"Confusion, crédulité, mauvaise interprétation des signes, peur excessive.",associations:"Sorbier · magie · discernement · protection · Dagda",magic:"Protection, lecture des signes et travail de discernement."},
"Fearn":{axes:"Engagement · fondation · courage · transformation",symbolism:"L'aulne relie symboliquement terre et eau. Résistant en milieu humide, il devient une image de construction, d'engagement et de solidité dans une situation mouvante.",reading:"Fearn invite à prendre position et à construire. Une décision demande d'être incarnée dans l'action et soutenue avec courage.",advice:"Engage-toi et construis sur des bases solides.",shadow:"Indécision, engagement fragile, fuite devant l'épreuve ou rigidité défensive.",associations:"Aulne · eau et terre · construction · protection · musique",magic:"Soutien symbolique aux engagements, fondations et passages difficiles."},
"Saille":{axes:"Cycles · intuition · réceptivité · souplesse",symbolism:"Le saule, proche de l'eau et de la lune dans les lectures symboliques, évoque les cycles, la sensibilité et le mouvement. Sa souplesse rappelle qu'accompagner un changement peut être plus juste que lui résister.",reading:"Saille conseille d'écouter le rythme de la situation. Il peut parler d'intuition, d'émotions, de mémoire et d'une phase où il faut accepter le mouvement.",advice:"Suis le courant sans perdre ta direction.",shadow:"Passivité, hypersensibilité, instabilité émotionnelle ou refus des cycles.",associations:"Saule · eau · lune · féminin · Nechtan",magic:"Intuition, rêves, cycles et travail symbolique avec l'eau."},
"Nuin":{axes:"Connexion · axe · équilibre · connaissance",symbolism:"Le frêne peut être lu comme un axe reliant plusieurs niveaux du monde. Nuin met l'accent sur les relations entre les choses plutôt que sur les éléments pris séparément.",reading:"Nuin invite à prendre de la hauteur et à comprendre les liens : causes, conséquences, relations, répétitions. Une situation devient plus claire lorsqu'on la replace dans un ensemble.",advice:"Cherche les liens avant de juger les éléments séparément.",shadow:"Dispersion, déconnexion, difficulté à relier les informations ou perte d'axe.",associations:"Frêne · axe cosmique · trois mondes · Yggdrasil · connaissance",magic:"Connexion, compréhension des systèmes et recherche d'équilibre."},
"Huathe":{axes:"Pureté · protection · épreuve · résilience",symbolism:"L'aubépine, épine blanche, associe la blancheur et la protection de l'épine. Elle porte une symbolique de purification, de seuil, de maîtrise et, dans le folklore, de proximité avec le monde féerique.",reading:"Huathe peut annoncer une difficulté ou une peur à traverser. L'épreuve n'est pas recherchée pour elle-même : elle révèle ce qui doit être purifié, simplifié ou fortifié.",advice:"Traverse l'épreuve en éliminant ce qui n'est plus essentiel.",shadow:"Peur, austérité excessive, isolement, blocage sexuel ou sentiment de malchance.",associations:"Aubépine · Beltane · fées · chasteté · protection",magic:"Purification, protection et travail de seuil dans les pratiques contemporaines."},
"Duir":{axes:"Force · enracinement · endurance · souveraineté",symbolism:"Le chêne incarne solidité, longévité et puissance. Son image de roi de la forêt ouvre aussi sur l'autorité, la justice et la responsabilité qui accompagne la force.",reading:"Duir demande de tenir, de s'enraciner et de poursuivre avec patience. Il peut aussi attirer l'attention sur l'autorité, le droit ou la manière dont on exerce son pouvoir.",advice:"Fais de ta force un appui stable, pas une arme.",shadow:"Obstination, inflexibilité, autoritarisme, excès ou manque de force.",associations:"Chêne · Dagda · Zeus/Jupiter · Thor · justice · seuil",magic:"Force, protection, stabilité et expansion, avec vigilance face à l'inflexibilité."},
"Tinne":{axes:"Action · courage · protection · canalisation",symbolism:"Le houx reste vert au cœur de l'hiver et se protège par ses feuilles épineuses. Il associe vitalité persistante, défense et énergie combative à canaliser vers une action juste.",reading:"Tinne demande souvent d'agir : sortir de la passivité, défendre, décider ou mobiliser son énergie. Pour une personne déjà impulsive, il conseille au contraire de maîtriser colère et violence.",advice:"Mobilise ta force, puis donne-lui une direction juste.",shadow:"Agressivité, vengeance, jalousie, impatience, violence ou passivité impuissante.",associations:"Houx · Dagda · guerre · foudre · forgeron · Roi-Houx",magic:"Protection et déblocage de l'énergie créative ou du travail manuel."},
"Coll":{axes:"Sagesse · étude · intuition · inspiration",symbolism:"Le noisetier est lié à la connaissance et au saumon de sagesse dans les récits irlandais. La noisette protégée par sa coque devient une image de la vérité qui demande patience et recherche.",reading:"Coll indique une période favorable à l'étude, à l'approfondissement ou à la recherche. Il invite à unir réflexion, expérience et intuition plutôt qu'à accumuler du savoir sans l'intégrer.",advice:"Cherche patiemment et transforme le savoir en sagesse.",shadow:"Superficialité, difficulté d'apprentissage, rejet de l'intuition ou blocage créatif.",associations:"Noisetier · saumon de sagesse · neuf · bardes · poésie",magic:"Connaissance de soi, signes, présages et approfondissement d'un savoir."},
"Quert":{axes:"Choix · vitalité · amour · régénération",symbolism:"Le pommier et la pomme sont associés dans de nombreux récits à l'Autre Monde, à la jeunesse, à la guérison et à l'amour. Quert relie ces thèmes à la nécessité de choisir ce que l'on veut faire vivre.",reading:"Quert peut concerner la santé, l'amour ou une décision importante. Il demande de peser les possibilités puis de s'engager, tout en prenant soin de ce qui nourrit réellement la vie.",advice:"Choisis ce que tu veux nourrir et engage-toi envers ce choix.",shadow:"Indécision, frustration, difficulté à s'engager, déséquilibre ou problématique amoureuse.",associations:"Pommier · Avalon · Morgane · jeunesse · amour · Autre Monde",magic:"Guérison, amour, régénération et travail autour des choix."},
"Muin":{axes:"Libération · expression · sensualité · initiation",symbolism:"La vigne s'enroule, relie et produit le vin, boisson chargée d'une forte symbolique de transformation. Elle évoque à la fois le lien, l'ivresse, le plaisir et la libération des inhibitions.",reading:"Muin invite à identifier ce qui entrave l'expression ou la liberté. Il peut encourager joie, intuition et communication, tout en mettant en garde contre contrôle, dépendance ou manipulation.",advice:"Desserre ce qui t'entrave et trouve ta propre voix.",shadow:"Addiction, fuite du réel, dépendance, manipulation, emprise ou perte de contrôle.",associations:"Vigne · vin · spirale · agriculture · Bres · extase",magic:"Expression de soi, libération de la parole et transformation des blocages."},
"Gort":{axes:"Lien · fidélité · abondance · transformation",symbolism:"Le lierre s'attache durablement à son support et reste vert. Il évoque fidélité, enlacement, désir et persistance, mais rappelle qu'un lien solide peut aussi devenir étouffant.",reading:"Gort attire l'attention sur les liens que l'on cultive. Il peut parler d'amour, de fidélité, de gratitude et de projet à faire fructifier, ou demander de reconnaître une dépendance.",advice:"Cultive les liens qui te nourrissent sans perdre ta liberté.",shadow:"Possessivité, dépendance, amour étouffant, infidélité ou sentiment d'être perdu.",associations:"Lierre · Dionysos · Ogmios · Tristan et Yseult · spirale",magic:"Travaux de longue durée, liens, protection et maturation d'un projet."},
"Ngetal":{axes:"Vitalité · guérison · équilibre · fertilité · direction",symbolism:"Le roseau est à la fois souple et résistant : il plie puis retrouve sa verticalité. Cette image fait de Ngetal un symbole d'adaptation qui ne sacrifie pas l'axe intérieur.",reading:"Ngetal demande d'ajuster sa manière d'avancer. Il peut aussi signaler croissance, créativité, prospérité ou nécessité de retrouver un équilibre dans ses habitudes de vie.",advice:"Reste souple dans tes moyens et ferme sur ce qui compte.",shadow:"Rigidité et résistance au changement, ou à l'inverse soumission, indécision et perte de direction.",associations:"Roseau · eau · souffle · musique · fertilité · Cernunnos (lecture moderne)",magic:"Guérison, équilibre, adaptation, croissance et recherche de direction."},
"Straif":{axes:"Destin · crise · protection · transformation",symbolism:"Le prunellier associe épines sombres et floraison blanche. Barrière naturelle, il devient une image de protection, d'adversité et de transformation d'une expérience douloureuse.",reading:"Straif signale souvent un événement imposé, imprévisible ou difficile. Le travail consiste moins à contrôler l'événement qu'à choisir la réponse et à transformer l'épreuve en prise de conscience.",advice:"Transforme ce que tu ne peux éviter en matière d'évolution.",shadow:"Accablement, révolte stérile, dépression, conflit, manipulation ou fascination pour le négatif.",associations:"Prunellier · épine noire · destin · orage · occultisme",magic:"Protection, révélation de ce qui est caché et rites de transformation."},
"Ruis":{axes:"Régénération · impermanence · transition · mouvement",symbolism:"Le sureau repousse avec vigueur après avoir été coupé. Il représente ainsi la roue du temps, la fin d'un état et la capacité de régénération qui lui succède.",reading:"Ruis annonce changement, passage ou nécessité de tourner une page. Il peut aussi évoquer mouvement, voyage et émotions intenses qu'il faut accompagner sans s'y laisser emporter.",advice:"Accepte que la roue tourne et libère la place pour le nouveau.",shadow:"Stagnation, refus d'évoluer, attachement au passé, passion incontrôlée ou difficulté de mobilité.",associations:"Sureau · Samhain · roue · Dagda · cheval · voyage",magic:"Transformation et énergie passionnelle ; symbolique puissante à tempérer."},
"Ailim":{axes:"Naissance · élévation · confiance · guidance",symbolism:"Le sapin reste vert pendant l'hiver et se dresse vers les hauteurs. Il évoque permanence de la vie, renouveau, élévation et capacité à regarder une situation avec recul.",reading:"Ailim marque un seuil et un premier pas. Il encourage confiance, constance et prise de hauteur, et peut représenter un guide, un enseignant ou une responsabilité nouvelle.",advice:"Prends de la hauteur, puis ose le premier pas.",shadow:"Manque d'espoir, inconstance, vision obscurcie, orgueil ou prétention.",associations:"Sapin · hiver · Yule (parallèle nordique) · naissance · guide",magic:"Commencement, confiance, élévation et travail de méditation."},
"Ohn":{axes:"Souveraineté · synthèse · organisation · direction",symbolism:"L'ajonc, persistant, épineux et couvert de fleurs jaunes, possède une forte dimension solaire. Ohn relie rayonnement et souveraineté à la capacité de réunir des forces diverses et de les organiser.",reading:"Ohn interroge la manière dont tu rayonnes et exerces ton pouvoir. Il peut annoncer joie, réussite et reconnaissance, ou inviter à rassembler connaissances et expériences pour en faire un ensemble cohérent.",advice:"Rassemble tes forces, choisis ta direction et laisse ta lumière rayonner.",shadow:"Orgueil, égocentrisme, abus de pouvoir, besoin de reconnaissance ou, inversement, timidité et effacement.",associations:"Ajonc · soleil · Lug · abeille · aigle · souveraineté",magic:"Remise en mouvement, orientation d'un projet et travail autour du rayonnement."},
"Ur":{axes:"Soin · purification · compassion · intuition",symbolism:"La bruyère pousse sur des terres pauvres et résiste aux éléments. Dans cette lecture, elle relie Terre et invisible, simplicité et capacité de purification ; tes notes associent aussi Ur au gui.",reading:"Ur invite à soigner, purifier ou rechercher la cause profonde d'un malaise. Il peut également parler de fin définitive et de deuil : ce qui retourne à la terre change de forme.",advice:"Soigne ce qui peut l'être et accepte de laisser partir ce qui est terminé.",shadow:"Matérialisme, égocentrisme, maladie, refus de la fin ou sacrifice de soi excessif.",associations:"Bruyère · gui · Dian Cécht · source de santé · terre",magic:"Ancrage, offrandes, coupure de liens et communication symbolique avec les esprits."},
"Eadha":{axes:"Communication · transmission · mobilité · expression",symbolism:"Les feuilles du peuplier tremble réagissent au moindre souffle. L'arbre devient ainsi une image de l'air, de la voix, du langage et de la circulation des idées.",reading:"Eadha attire l'attention sur ce qui doit être dit, appris ou transmis. Il encourage à briser le silence, à développer souplesse mentale et mobilité, et à comprendre les peurs qui bloquent l'expression.",advice:"Fais circuler la parole et donne une voix à ce qui restait silencieux.",shadow:"Timidité, mensonge, médisance, difficulté à communiquer, contradictions internes ou angoisse.",associations:"Peuplier · air · souffle · bardes · Ogmios · bouclier",magic:"Rêves, visions, divination et clarification de l'interprétation."},
"Ioho":{axes:"Éternité · mort/renaissance · mémoire · stabilité",symbolism:"L'if associe longévité exceptionnelle, feuillage persistant et forte toxicité. Il réunit donc de façon saisissante permanence de la vie et proximité de la mort.",reading:"Ioho peut accompagner un deuil réel ou symbolique, une rupture ou une transformation profonde. Il rappelle que la fin d'une forme n'est pas nécessairement la fin du processus.",advice:"Accepte la fin, reste enraciné et laisse la vie changer de forme.",shadow:"Peur de la mort, instabilité, manque de concentration, de fiabilité ou de persévérance.",associations:"If · Samhain · axe cosmique · mémoire · arc · immortalité",magic:"Mémoire, ancêtres, histoire personnelle et intégration des leçons du passé."},
"Eabadh/Koad":{axes:"Sacré · transcendance · sagesse · justice",symbolism:"Le bosquet sacré représente un espace séparé du quotidien où nature, culte, connaissance et justice peuvent se rencontrer. Il est davantage un lieu symbolique qu'une essence unique.",reading:"Eabadh invite à prendre du recul, retrouver le sens du sacré et replacer sa situation dans un ensemble plus vaste. Il peut aussi questionner justice, valeurs et cohérence spirituelle.",advice:"Entre dans le silence et cherche ta juste place dans le Tout.",shadow:"Rejet du sacré, matérialisme fermé, orgueil spirituel, fanatisme ou sentiment d'épreuve imposée.",associations:"Bosquet · sanctuaire · druide · Merlin · source · justice",magic:"Recueillement, méditation, quête de transcendance et travail dans un espace consacré."},
"Oir/Tharan":{axes:"Foudre · destin · révélation · transformation",symbolism:"Le fusain est lié dans tes notes au fuseau et à la foudre : deux images du destin, l'une qui file les événements, l'autre qui frappe soudainement et relie ciel et terre.",reading:"Oir peut annoncer un choc, une rupture de rythme ou une intuition fulgurante. L'événement échappe parfois au contrôle, mais la réponse et le sens qu'on lui donne restent ouverts.",advice:"Observe ce que le choc révèle avant de réagir.",shadow:"Colère explosive, violence, fatalisme, accident, effondrement ou sentiment d'être brûlé par l'événement.",associations:"Fusain · foudre · Taranis · Dagda · fuseau · destin",magic:"Révélation, transformation rapide et attention aux signes ou synchronicités."},
"Uilleand":{axes:"Lien · amour · évolution · initiation",symbolism:"Le chèvrefeuille s'enroule rapidement autour de son support. Comme le lierre, il représente fidélité et enlacement, mais sa spirale ouvre davantage sur l'idée de chemin initiatique et d'évolution.",reading:"Uilleand peut annoncer une relation solide ou interroger la qualité d'un engagement. Dans une quête intérieure, il accepte détours et phases de désorientation comme parties du chemin.",advice:"Enlace sans emprisonner, avance sans te perdre.",shadow:"Jalousie, possessivité, amour étouffant, infidélité, hésitation ou perte de repères.",associations:"Chèvrefeuille · spirale · labyrinthe · Tristan et Yseult · serpent",magic:"Liens, visions, évolution intérieure et, dans les traditions modernes, magie liante."},
"Phagos":{axes:"Mémoire · écrit · héritage · expérience",symbolism:"Le hêtre est fortement associé dans les traditions européennes aux tablettes, à l'écriture et au livre. Phagos devient ainsi un symbole de mémoire conservée et de savoir transmis.",reading:"Phagos conseille de chercher dans les écrits ou dans l'expérience passée. Il peut inviter à écrire, étudier ses souvenirs, comprendre un schéma répétitif ou décider ce qui mérite d'être transmis.",advice:"Appuie-toi sur le passé sans lui abandonner ton présent.",shadow:"Poids de l'héritage, répétition de vieux schémas, fixation sur le passé ou mémoire douloureuse.",associations:"Hêtre · livre · écriture · Ogme · ancêtres · tradition",magic:"Travail symbolique sur la mémoire, les ancêtres et la transmission."},
"Mor":{axes:"Profondeur · passage · inconscient · transformation",symbolism:"La mer est à la fois origine, frontière et immensité. Mor clôt le parcours en réunissant matrice primordiale, passage vers l'Autre Monde et profondeur de l'inconscient.",reading:"Mor invite à descendre sous les apparences : rêves, intuition, inconscient, rapport à la mort ou transformation intérieure. Il peut signaler un passage majeur et la nécessité de faire confiance à une vision plus globale.",advice:"Traverse les profondeurs sans oublier ton point d'ancrage.",shadow:"Se sentir perdu, submergé ou coupé de tout sens ; désespoir profond et perte de repères.",associations:"Mer · Tir na nÓg · Manannán · navigation · destin · Autre Monde",magic:"Voyage intérieur, intuition, divination et transformation de la conscience."}
};


const REVISION_ALIASES={
  "Eabadh/Koad":"Eabadh/Koad", "Oir/Tharan":"Oir/Tharan"
};
function revisionFor(name){ return REVISION[name] || REVISION[REVISION_ALIASES[name]] || null; }
function panels(id){document.querySelectorAll('.panel').forEach(x=>x.classList.remove('active'));$(id).classList.add('active');scrollTo(0,0)}
function shuffle(a){return [...a].sort(()=>Math.random()-.5)}
function namesExcept(name, hard=false){
 let pool=OGHAMS.map(x=>x.name).filter(x=>x!==name);
 if(hard&&CLOSE[name]){
   const close=shuffle(CLOSE[name].filter(n=>n!==name));
   const rest=shuffle(pool.filter(x=>!close.includes(x)));
   return [...close,...rest];
 }
 return shuffle(pool);
}
function choices(correct, field, hard){
 let r=OGHAMS.find(x=>x.name===correct), vals=[r[field]];
 let preferred=hard&&CLOSE[correct]?shuffle(CLOSE[correct]).map(n=>OGHAMS.find(x=>x.name===n)?.[field]).filter(Boolean):[];
 for(let v of [...preferred,...shuffle(OGHAMS.map(x=>x[field]))]) if(v&& !vals.includes(v)) vals.push(v); 
 return shuffle(vals.slice(0,4));
}
function makeQuestion(o,type,hard){
 if(type==='tree') return {type:'Plante associée',q:`Quel Ogham est associé à « ${o.tree} » ?`,a:o.name,opts:shuffle([o.name,...namesExcept(o.name,hard).slice(0,3)]),o};
 if(type==='theme') return {type:'Thème central',q:`Quel Ogham a pour thème central « ${o.theme} » ?`,a:o.name,opts:shuffle([o.name,...namesExcept(o.name,hard).slice(0,3)]),o};
 if(type==='sound') return {type:'Valeur phonétique',q:`Quelle valeur phonétique correspond à ${o.name} ?`,a:o.sound,opts:choices(o.name,'sound',hard),o};
 if(type==='symbol') return {type:'Symbole',q:`<img class="question-symbol" src="${o.image}" alt="Symbole oghamique à identifier"><span>Quel nom correspond à ce symbole ?</span>`,html:true,a:o.name,opts:shuffle([o.name,...namesExcept(o.name,hard).slice(0,3)]),o};
 return {type:'Mots-clés',q:`À quel Ogham associes-tu : ${o.keywords || o.theme} ?`,a:o.name,opts:shuffle([o.name,...namesExcept(o.name,hard).slice(0,3)]),o};
}
function build(mode, subset){
 let pool=subset?.length?OGHAMS.filter(o=>subset.includes(o.name)):OGHAMS;
 let count=mode==='errors'?Math.min(15,pool.length*2):15, types=['tree','theme','sound','symbol','keywords'], qs=[];
 for(let i=0;i<count;i++){let o=pool[i%pool.length]; if(i%pool.length===0) pool=shuffle(pool); qs.push(makeQuestion(o,types[i%types.length],mode==='hard'))}
 return shuffle(qs);
}
function startQuiz(mode){state={questions:build(mode),i:0,score:0,wrong:[],mode};panels('quiz');renderQ()}
function startErrors(){let e=JSON.parse(localStorage.getItem('oghamErrors')||'[]');if(!e.length){alert("Aucune erreur enregistrée pour le moment.");return}state={questions:build('errors',e),i:0,score:0,wrong:[],mode:'errors'};panels('quiz');renderQ()}
function renderQ(){
 let q=state.questions[state.i];$('progress').textContent=`${state.i+1} / ${state.questions.length}`;$('bar').style.width=`${state.i/state.questions.length*100}%`;
 $('qtype').textContent=q.type;if(q.html){$('question').innerHTML=q.q}else{$('question').textContent=q.q};$('feedback').className='feedback';$('feedback').innerHTML='';$('next').className='next';
 $('answers').innerHTML='';q.opts.forEach(v=>{let b=document.createElement('button');b.textContent=v;b.onclick=()=>answer(v,b);$('answers').appendChild(b)})
}
function cleanRevisionText(o){
 let text=(o.synthesis||o.interpretation||'').trim();
 // Les anciennes synthèses contenaient à la fin un récapitulatif cumulatif des Oghams précédents.
 // On le retire du corrigé pour rester concentré sur l'Ogham de la question.
 text=text.split(/###\s+(?:Les|La progression)/i)[0].trim();
 text=text.replace(/###\s*/g,'').replace(/\s+/g,' ').trim();
 return text;
}
function answer(v,b){
 let q=state.questions[state.i],ok=v===q.a;document.querySelectorAll('#answers button').forEach(x=>{x.disabled=true;if(x.textContent===q.a)x.classList.add('correct')});if(!ok){b.classList.add('wrong');state.wrong.push(q.o.name)}else state.score++;
 const detail=cleanRevisionText(q.o);
 $('feedback').innerHTML=`
   <div class="feedback-status">${ok?'✓ Bonne réponse':'Réponse : '+q.a}</div>
   <div class="feedback-head"><img class="feedback-symbol" src="${q.o.image}" alt="${q.o.name}"><div><b>${q.o.name}</b><span>${q.o.tree} · ${q.o.sound}</span></div></div>
   <div class="feedback-theme"><span>Thème central</span><b>${q.o.theme}</b></div>
   ${detail?`<div class="feedback-detail feedback-quote">${detail}</div>`:''}
   ${revisionFor(q.o.name)?`<div class="revision-grid">
     <div class="revision-item revision-wide"><span>Axes secondaires</span><p>${revisionFor(q.o.name).axes}</p></div>
     <div class="revision-item"><span>Symbolique essentielle</span><p>${revisionFor(q.o.name).symbolism}</p></div>
     <div class="revision-item"><span>En tirage</span><p>${revisionFor(q.o.name).reading}</p></div>
     <div class="revision-item revision-advice"><span>Conseil</span><p>${revisionFor(q.o.name).advice}</p></div>
     <div class="revision-item revision-shadow"><span>Ombre</span><p>${revisionFor(q.o.name).shadow}</p></div>
     <div class="revision-item"><span>Associations</span><p>${revisionFor(q.o.name).associations}</p></div>
     <div class="revision-item"><span>Magie</span><p>${revisionFor(q.o.name).magic}</p></div>
   </div>`:''}
   <div class="feedback-keywords"><b>À retenir :</b> ${q.o.keywords}</div>`;
 $('feedback').classList.add('show');$('next').classList.add('show')
}
function nextQuestion(){state.i++;if(state.i>=state.questions.length)return finish();renderQ()}
function finish(){
 let pct=Math.round(state.score/state.questions.length*100), old=JSON.parse(localStorage.getItem('oghamErrors')||'[]'), merged=[...new Set([...old,...state.wrong])];
 if(state.wrong.length===0 && state.mode==='errors') localStorage.removeItem('oghamErrors'); else localStorage.setItem('oghamErrors',JSON.stringify(merged));
 localStorage.setItem('oghamLast',JSON.stringify({score:state.score,total:state.questions.length,pct}));
 $('score').textContent=`${pct}%`;$('resultText').innerHTML=`${state.score} bonnes réponses sur ${state.questions.length}.`+(state.wrong.length?`<br><br>À revoir : <b>${[...new Set(state.wrong)].join(', ')}</b>.`:`<br><br><b>Parcours sans faute.</b>`);panels('result');updateStats()
}
function goHome(){panels('home');updateStats()}
function showCards(){panels('cards');renderCards('')}
function renderCards(q){
 q=(q||'').toLowerCase();let list=OGHAMS.filter(o=>JSON.stringify(o).toLowerCase().includes(q));
 $('cardgrid').innerHTML=list.map(o=>`<article class="card"><div class="sym"><img src="${o.image}" alt="Symbole ${o.name}"></div><h3>${o.name}</h3><div class="meta">n° ${o.order} · ${o.tree} · ${o.sound}</div><span class="pill">${o.theme}</span><div class="quote">${o.synthesis||o.keywords}</div></article>`).join('')
}
function updateStats(){let last=JSON.parse(localStorage.getItem('oghamLast')||'null'),errs=JSON.parse(localStorage.getItem('oghamErrors')||'[]');$('stats').textContent=(last?`Dernier score : ${last.pct}% · `:'')+`${errs.length} ogham${errs.length>1?'s':''} à revoir`;$('errorsBtn').style.opacity=errs.length?1:.55}
updateStats();
